"""
Response and request schemas are defined here.
"""

from .functional_zones import FunctionalZoneData, FunctionalZoneType, FunctionalZoneTypePost
from .health_check import PingResponse
from .indicators import (
    Indicator,
    IndicatorsGroup,
    IndicatorsGroupPost,
    IndicatorsPatch,
    IndicatorsPost,
    IndicatorsPut,
    IndicatorValue,
    IndicatorValuePost,
    MeasurementUnit,
    MeasurementUnitPost,
)
from .living_buildings import (
    LivingBuildingsData,
    LivingBuildingsDataPatch,
    LivingBuildingsDataPost,
    LivingBuildingsDataPut,
    LivingBuildingsWithGeometry,
)
from .normatives import Normative, NormativeDelete, NormativePatch, NormativePost
from .object_geometries import ObjectGeometries, ObjectGeometriesPatch, ObjectGeometriesPost, ObjectGeometriesPut
from .pages import Page
from .physical_object_types import (
    PhysicalObjectFunction,
    PhysicalObjectFunctionPatch,
    PhysicalObjectFunctionPost,
    PhysicalObjectFunctionPut,
    PhysicalObjectsTypes,
    PhysicalObjectsTypesHierarchy,
    PhysicalObjectsTypesPatch,
    PhysicalObjectsTypesPost,
)
from .physical_objects import (
    PhysicalObjectsData,
    PhysicalObjectsDataPatch,
    PhysicalObjectsDataPost,
    PhysicalObjectsDataPut,
    PhysicalObjectsWithTerritory,
    PhysicalObjectWithGeometry,
    PhysicalObjectWithGeometryPost,
)
from .profiles_reclamation import (
    ProfilesReclamationData,
    ProfilesReclamationDataMatrix,
    ProfilesReclamationDataPost,
    ProfilesReclamationDataPut,
)
from .projects import (
    Project,
    ProjectPatch,
    ProjectPost,
    ProjectPut,
    ProjectTerritory,
    ProjectTerritoryPatch,
    ProjectTerritoryPost,
    ProjectTerritoryPut,
)
from .projects_functional_zones import (
    ProjectsFunctionalZone,
    ProjectsFunctionalZonePatch,
    ProjectsFunctionalZonePost,
    ProjectsFunctionalZonePut,
)
from .projects_indicators import (
    ProjectsIndicator,
    ProjectsIndicatorPost,
)
from .scenarios import ScenariosData, ScenariosPatch, ScenariosPost, ScenariosPut
from .scenarios_urban_objects import ScenariosUrbanObject
from .service_types import (
    ServiceTypes,
    ServiceTypesHierarchy,
    ServiceTypesPatch,
    ServiceTypesPost,
    ServiceTypesPut,
    UrbanFunction,
    UrbanFunctionPatch,
    UrbanFunctionPost,
    UrbanFunctionPut,
)
from .services import (
    ServicesCountCapacity,
    ServicesData,
    ServicesDataPatch,
    ServicesDataPost,
    ServicesDataPut,
    ServicesDataWithGeometry,
    ServiceWithTerritories,
)
from .territories import (
    TerritoryData,
    TerritoryDataPatch,
    TerritoryDataPost,
    TerritoryDataPut,
    TerritoryType,
    TerritoryTypesPost,
    TerritoryWithIndicator,
    TerritoryWithIndicators,
    TerritoryWithNormatives,
    TerritoryWithoutGeometry,
)

__all__ = [
    "PingResponse",
    "TerritoryType",
    "TerritoryTypesPost",
    "TerritoryData",
    "TerritoryDataPost",
    "TerritoryDataPatch",
    "TerritoryDataPut",
    "TerritoryWithIndicator",
    "TerritoryWithIndicators",
    "TerritoryWithNormatives",
    "TerritoryWithoutGeometry",
    "ScenariosData",
    "ScenariosPatch",
    "ScenariosPost",
    "ScenariosPut",
    "ScenariosUrbanObject",
    "ServicesCountCapacity",
    "ServicesData",
    "ServicesDataPatch",
    "ServicesDataPost",
    "ServicesDataPut",
    "ServicesDataWithGeometry",
    "ServiceWithTerritories",
    "ServiceTypes",
    "ServiceTypesHierarchy",
    "ServiceTypesPatch",
    "ServiceTypesPost",
    "ServiceTypesPut",
    "Indicator",
    "IndicatorsGroup",
    "IndicatorsGroupPost",
    "IndicatorsPatch",
    "IndicatorsPost",
    "IndicatorsPut",
    "IndicatorValue",
    "IndicatorValuePost",
    "MeasurementUnit",
    "MeasurementUnitPost",
    "Normative",
    "NormativeDelete",
    "NormativePatch",
    "NormativePost",
    "ObjectGeometries",
    "ObjectGeometriesPatch",
    "ObjectGeometriesPost",
    "ObjectGeometriesPut",
    "PhysicalObjectsData",
    "PhysicalObjectsDataPatch",
    "PhysicalObjectsDataPost",
    "PhysicalObjectWithGeometryPost",
    "PhysicalObjectsWithTerritory",
    "PhysicalObjectsDataPut",
    "PhysicalObjectWithGeometry",
    "PhysicalObjectFunction",
    "PhysicalObjectFunctionPatch",
    "PhysicalObjectFunctionPost",
    "PhysicalObjectFunctionPut",
    "PhysicalObjectsTypes",
    "PhysicalObjectsTypesHierarchy",
    "PhysicalObjectsTypesPatch",
    "PhysicalObjectsTypesPost",
    "LivingBuildingsData",
    "LivingBuildingsDataPatch",
    "LivingBuildingsDataPost",
    "LivingBuildingsDataPut",
    "LivingBuildingsWithGeometry",
    "FunctionalZoneData",
    "FunctionalZoneType",
    "FunctionalZoneTypePost",
    "UrbanFunction",
    "UrbanFunctionPatch",
    "UrbanFunctionPost",
    "UrbanFunctionPut",
    "Page",
    "Project",
    "ProjectPost",
    "ProjectPut",
    "ProjectPatch",
    "ProjectTerritory",
    "ProjectTerritoryPost",
    "ProjectTerritoryPut",
    "ProjectTerritoryPatch",
    "ProfilesReclamationData",
    "ProfilesReclamationDataPost",
    "ProfilesReclamationDataPut",
    "ProfilesReclamationDataMatrix",
    "ProjectsIndicator",
    "ProjectsIndicatorPost",
    "ProjectsFunctionalZone",
    "ProjectsFunctionalZonePost",
    "ProjectsFunctionalZonePut",
    "ProjectsFunctionalZonePatch",
]
